### ISSUE TITLE
Error on docker-compose [Linux]

### ISSUE THREAD

**Issue by patataofcourse** [revoltchat/self-hosted#6]
Although the error seems to cause a bunch more exceptions, I only included the first one.
This happens when running `docker-compose up -d`.
I'm using Manjaro Linux.
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/http/client.py", line 1257, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1303, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1252, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1012, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 952, in send
    self.connect()
  File "/usr/lib/python3.9/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by patataofcourse** [comment]
Forgot to say, this is using the .env.example

**Comment by theAkito** [comment]
Something like this?

https://github.com/plankanban/planka/issues/133

If yes, this should be the thing you check next:

https://github.com/plankanban/planka/issues/133#issuecomment-903120822

**Comment by patataofcourse** [comment]
Yep, that's the error. However, reinstalling docker and docker-compose did nothing for me :/

**Comment by theAkito** [comment]
What's the result of the test from the referenced comment?

**Comment by insertish** [comment]
This appears to be an issue with Docker and not the repository, closing unless if you have anything to the contrary.
