### ISSUE TITLE
bug: bonfire minio/mc eqalpha/keydb can't start

### ISSUE THREAD

**Issue by huajiba** [revoltchat/self-hosted#92]
### What happened?

![image](https://github.com/user-attachments/assets/213b419c-0075-4068-98b0-18b8055e4188)
## revolt_events_1
```
la02@la02:~/docker/revolt$ docker logs revolt_events_1
 INFO  revolt_config > Starting revolt-bonfire@0.7.14
thread 'main' panicked at 'Redis connection: FailedConnection', /home/rust/src/crates/core/presence/src/lib.rs:166:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 INFO  revolt_config > Starting revolt-bonfire@0.7.14
thread 'main' panicked at 'Redis connection: FailedConnection', /home/rust/src/crates/core/presence/src/lib.rs:166:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 INFO  revolt_config > Starting revolt-bonfire@0.7.14
thread 'main' panicked at 'Redis connection: FailedConnection', /home/rust/src/crates/core/presence/src/lib.rs:166:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 INFO  revolt_config > Starting revolt-bonfire@0.7.14
thread 'main' panicked at 'Redis connection: FailedConnection', /home/rust/src/crates/core/presence/src/lib.rs:166:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 INFO  revolt_config > Starting revolt-bonfire@0.7.14
thread 'main' panicked at 'Redis connection: FailedConnection', /home/rust/src/crates/core/presence/src/lib.rs:166:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 INFO  revolt_config > Starting revolt-bonfire@0.7.14
thread 'main' panicked at 'Redis connection: FailedConnection', /home/rust/src/crates/core/presence/src/lib.rs:166:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 INFO  revolt_config > Starting revolt-bonfire@0.7.14
thread 'main' panicked at 'Redis connection: FailedConnection', /home/rust/src/crates/core/presence/src/lib.rs:166:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 INFO  revolt_config > Starting revolt-bonfire@0.7.14
thread 'main' panicked at 'Redis connection: FailedConnection', /home/rust/src/crates/core/presence/src/lib.rs:166:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 INFO  revolt_config > Starting revolt-bonfire@0.7.14
thread 'main' panicked at 'Redis connection: FailedConnection', /home/rust/src/crates/core/presence/src/lib.rs:166:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 INFO  revolt_config > Starting revolt-bonfire@0.7.14
thread 'main' panicked at 'Redis connection: FailedConnection', /home/rust/src/crates/core/presence/src/lib.rs:166:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 INFO  revolt_config > Starting revolt-bonfire@0.7.14
thread 'main' panicked at 'Redis connection: FailedConnection', /home/rust/src/crates/core/presence/src/lib.rs:166:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 INFO  revolt_config > Starting revolt-bonfire@0.7.14
thread 'main' panicked at 'Redis connection: FailedConnection', /home/rust/src/crates/core/presence/src/lib.rs:166:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 INFO  revolt_config > Starting revolt-bonfire@0.7.14
thread 'main' panicked at 'Redis connection: FailedConnection', /home/rust/src/crates/core/presence/src/lib.rs:166:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 INFO  revolt_config > Starting revolt-bonfire@0.7.14
thread 'main' panicked at 'Redis connection: FailedConnection', /home/rust/src/crates/core/presence/src/lib.rs:166:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 INFO  revolt_config > Starting revolt-bonfire@0.7.14
thread 'main' panicked at 'Redis connection: FailedConnection', /home/rust/src/crates/core/presence/src/lib.rs:166:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 INFO  revolt_config > Starting revolt-bonfire@0.7.14
thread 'main' panicked at 'Redis connection: FailedConnection', /home/rust/src/crates/core/presence/src/lib.rs:166:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
## revolt_createbuckets_1
```
la02@la02:~/docker/revolt$ docker logs revolt_createbuckets_1
Added `minio` successfully.
The cluster is ready
mc: <ERROR> Unable to make bucket `minio/attachments`. Your previous request to create the named bucket succeeded and you already own it.
mc: <ERROR> Unable to make bucket `minio/avatars`. Your previous request to create the named bucket succeeded and you already own it.
mc: <ERROR> Unable to make bucket `minio/backgrounds`. Your previous request to create the named bucket succeeded and you already own it.
mc: <ERROR> Unable to make bucket `minio/icons`. Your previous request to create the named bucket succeeded and you already own it.
mc: <ERROR> Unable to make bucket `minio/banners`. Your previous request to create the named bucket succeeded and you already own it.
mc: <ERROR> Unable to make bucket `minio/emojis`. Your previous request to create the named bucket succeeded and you already own it.
```
## revolt_redis_1 did not generate any logs
```
la02@la02:~/docker/revolt$ docker logs revolt_redis_1
la02@la02:~/docker/revolt$
```

**Comment by huajiba** [comment]
#91 add Revolt.toml file
